# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
# baseURL: "https://tyliu22.github.io/hugo-PaperMod/"
baseURL: "https://tyliu22.github.io/"
# baseURL: "https://Tianyu-Liu11.github.io/"
title: Tianyu Liu
paginate: 5
theme: [hugo-PaperMod]
publishDir: "public"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod","model"]
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "Blog"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archives
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Snoopy
          url: https://www.peanuts.com/about/snoopy

    # You can swith the website mode by 
    # 1. annotating the follwoig <params> and then turn off the  
    # 2.   profileMode:
    #    enabled: false # false
    params:
      languageAltTitle: test
      profileMode:
        enabled: true
        title: Tianyu Liu
        imageUrl: "https://static.wixstatic.com/media/449abe_7b15686b2118476da4a733a7861dd772~mv2.jpg/v1/fill/w_998,h_998,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/sn-color.jpg"
        # "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
        imageTitle: ProfileMode image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "🥝 🥑 🍊 🍳 🦐 | Machine Learning Engineer 🐶 |  ☀ 🌧 ❄ 🌙 📱 "
        buttons:
          - name: Blog
            # url: public/posts/index.html
            url: posts
          - name: Code
            url: model

outputs:
  home:
    - HTML
    # - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod"
  author: Snoopy
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  # images: ["images/papermod-cover.png"]

  profileMode:
    enabled: true # false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Tianyu Liu"
    Content: >
      👋 Welcome to my personal page

      - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

      - Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .

  socialIcons:
    - name: linkedin
      title: View My Study/Work Experience on LinkedIn 
      url: "https://www.linkedin.com/in/tianyu-liu-1a1a141a2/"
    - name: googlescholar
      title: Give me a paper :)
      url: "https://scholar.google.com.au/citations?user=MjwnqU4AAAAJ&hl=en"
    - name: github
      title: View My Trash Code on Github
      url: "https://github.com/tyliu22"
    # - name: X
    #   title: Share PaperMod on X/Twitter
    #   url: "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"


  # editPost:
  #   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
